version: 1.0.{build}
cache: res\pidll.zip
build_script:
- cmd: >-
    if not exist res\pidll.zip curl -s -L -o res\pidll.zip "https://drive.google.com/uc?export=download&id=0B4J7WiY9w-uUZjRsaGFRbGZza28"

    7z x res\pidll.zip>NUL

    set PIHOME=pidll

    echo.|build.bat>"%TEMP%\out"
test_script:
- cmd: >-
    for /f "delims=" %%i in ('build\DBMTester.exe^|find "Unit tests"') do set message=%%i

    echo %message%|find "PASSED">NUL&&set result=Passed||set result=Failed

    appveyor AddTest "%message:~3%" -Framework "" -FileName "" -Outcome %result%

    for /f "delims=" %%i in ('build\DBMTester.exe^|find "Integration tests"') do set message=%%i

    echo %message%|find "PASSED">NUL&&set result=Passed||set result=Failed

    appveyor AddTest "%message:~3%" -Framework "" -FileName "" -Outcome %result%
deploy_script:
- cmd: >-
    for /f "delims=" %%i in ('build\DBMTester.exe^|find "DBM"') do set version=%%i

    7z a build\%version: =_%_bin.zip build\>NUL

    appveyor PushArtifact build\%version: =_%_bin.zip

    curl -s -L -o build\%version: =_%_src.zip https://github.com/jfitie/DBM/archive/master.zip

    appveyor PushArtifact build\%version: =_%_src.zip